#!/usr/bin/env python3
"""Build deterministic onboarding_smoke broadcast command JSON.

Generates `phase4.broadcast_commands.v1` payload using concrete
`credential_nft.aleo/mint_credential_nft` argument codec:
- 6x [u8;32] hex args
- 2x u16 args

The caller supplies a submit command prefix that already includes
CLI-specific flags (network/rpc/private-key/etc.). This avoids hardcoding
one CLI dialect in repo while keeping arg ordering deterministic.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
from pathlib import Path
from typing import Any

HEX32_RE = re.compile(r"^0x[a-fA-F0-9]{64}$")


def must_hex32(name: str, value: Any) -> str:
    if not isinstance(value, str) or not HEX32_RE.fullmatch(value):
        raise SystemExit(f"ERROR: {name} must be 0x-prefixed 32-byte hex (64 nybbles)")
    return value.lower()


def must_u16(name: str, value: Any) -> str:
    if not isinstance(value, int) or value < 0 or value > 65535:
        raise SystemExit(f"ERROR: {name} must be integer in [0, 65535]")
    if value == 0:
        raise SystemExit(f"ERROR: {name} must be non-zero for mint_credential_nft")
    return f"{value}u16"


def main() -> None:
    ap = argparse.ArgumentParser(description="Build onboarding_smoke PHASE4_BROADCAST_COMMANDS_JSON payload")
    ap.add_argument("--args-file", required=True, help="JSON file containing mint_credential_nft args")
    ap.add_argument(
        "--submit-prefix",
        required=True,
        help=(
            "Shell command prefix used to submit transition (must include executable/flags/program/transition). "
            "Example: \"snarkos developer execute credential_nft.aleo mint_credential_nft --private-key '$ALEO_PRIVATE_KEY' --query '$RPC_URL/broadcast'\""
        ),
    )
    ap.add_argument("--name", default="submit_onboarding", help="Command entry name")
    ap.add_argument("--out", default="-", help="Output file path or '-' for stdout")
    ns = ap.parse_args()

    data = json.loads(Path(ns.args_file).read_text(encoding="utf-8"))

    args = [
        must_hex32("credential_id_hex", data.get("credential_id_hex")),
        must_hex32("subject_hash_hex", data.get("subject_hash_hex")),
        must_hex32("issuer_hash_hex", data.get("issuer_hash_hex")),
        must_hex32("scope_hash_hex", data.get("scope_hash_hex")),
        must_hex32("doc_hash_hex", data.get("doc_hash_hex")),
        must_hex32("root_hex", data.get("root_hex")),
        must_u16("schema_v", data.get("schema_v")),
        must_u16("policy_v", data.get("policy_v")),
    ]

    encoded_args = " ".join(shlex.quote(v) for v in args)
    prefix = ns.submit_prefix.strip()
    if not prefix:
        raise SystemExit("ERROR: --submit-prefix must be non-empty")

    command = (
        "bash -lc "
        + shlex.quote(
            "set -euo pipefail; "
            f"out=$({prefix} {encoded_args} 2>&1); "
            "printf '%s\\n' \"$out\"; "
            "tx=$(printf '%s\\n' \"$out\" | sed -nE 's/.*([a-fA-F0-9]{64}).*/\\1/p' | head -n1); "
            "test -n \"$tx\"; "
            "echo \"transaction id: $tx\""
        )
    )

    payload = {
        "schema_version": "phase4.broadcast_commands.v1",
        "notes": [
            "Generated by scripts/build_onboarding_broadcast_commands.py",
            "Codec mapping: credential_nft.aleo/mint_credential_nft",
            "Args order: credential_id, subject_hash, issuer_hash, scope_hash, doc_hash, root, schema_v, policy_v",
        ],
        "commands": [{"name": ns.name, "command": command}],
    }

    out_text = json.dumps(payload, indent=2) + "\n"
    if ns.out == "-":
        print(out_text, end="")
    else:
        out_path = Path(ns.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(out_text, encoding="utf-8")


if __name__ == "__main__":
    main()
